import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const lineItem = v.object({
  pos: v.number(),
  description: v.string(),
  qty: v.number(),
  unit: v.string(),
  unitPrice: v.number(),
  total: v.number(),
  taxRate: v.optional(v.number()),
});

const taxBreakdownEntry = v.object({
  taxRate: v.number(),
  netAmount: v.number(),
  vatAmount: v.number(),
  grossAmount: v.number(),
});

export default defineSchema({
  users: defineTable({
    email: v.string(),
    name: v.string(),
    magicLinkToken: v.optional(v.string()),
    magicLinkExpiry: v.optional(v.number()),
    stripeCustomerId: v.optional(v.string()),
    stripeSubscriptionId: v.optional(v.string()),
    plan: v.string(),
    planStatus: v.string(),
    createdAt: v.number(),
    lastLoginAt: v.optional(v.number()),
  }).index("email", ["email"]).index("magicLinkToken", ["magicLinkToken"]).index("stripeCustomerId", ["stripeCustomerId"]),

  businessProfiles: defineTable({
    userId: v.id("users"),
    name: v.string(),
    street: v.string(),
    postalCityCountry: v.string(),
    country: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    legalForm: v.string(),
    bankOwner: v.optional(v.string()),
    iban: v.optional(v.string()),
    bic: v.optional(v.string()),
    currentUid: v.optional(v.string()),
    currentTaxStatus: v.string(),
    currentTaxRate: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("userId", ["userId"]),

  taxStatusHistory: defineTable({
    profileId: v.id("businessProfiles"),
    status: v.string(),
    rate: v.number(),
    validFrom: v.string(),
    validUntil: v.optional(v.string()),
    reason: v.optional(v.string()),
    changedAt: v.number(),
  }).index("profileId", ["profileId"]),

  uidHistory: defineTable({
    profileId: v.id("businessProfiles"),
    uid: v.string(),
    validFrom: v.string(),
    validUntil: v.optional(v.string()),
    changedAt: v.number(),
  }).index("profileId", ["profileId"]),

  customers: defineTable({
    userId: v.id("users"),
    name: v.string(),
    street: v.optional(v.string()),
    postalCityCountry: v.optional(v.string()),
    uid: v.optional(v.string()),
    email: v.optional(v.string()),
    notes: v.optional(v.string()),
    createdAt: v.number(),
  }).index("userId", ["userId"]),

  angebots: defineTable({
    userId: v.id("users"),
    number: v.string(),
    date: v.string(),
    validUntil: v.optional(v.string()),
    deliveryDate: v.optional(v.string()),
    recipientName: v.string(),
    recipientStreet: v.string(),
    recipientCity: v.string(),
    recipientUid: v.optional(v.string()),
    taxMode: v.string(),
    taxRate: v.number(),
    taxNote: v.optional(v.string()),
    taxBreakdown: v.optional(v.array(taxBreakdownEntry)),
    netAmount: v.number(),
    vatAmount: v.number(),
    grossAmount: v.number(),
    items: v.array(lineItem),
    status: v.string(),
    sentDate: v.optional(v.string()),
    sentTo: v.optional(v.string()),
    confirmedDate: v.optional(v.string()),
    pdfStorageId: v.optional(v.id("_storage")),
    auftragId: v.optional(v.id("auftrags")),
    paymentTerms: v.optional(v.string()),
    footer: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("userId", ["userId"]).index("number", ["userId", "number"]).index("auftragId", ["auftragId"]),

  auftrags: defineTable({
    userId: v.id("users"),
    number: v.string(),
    date: v.string(),
    deliveryDate: v.optional(v.string()),
    periodStart: v.optional(v.string()),
    periodEnd: v.optional(v.string()),
    customerId: v.optional(v.id("customers")),
    recipientName: v.string(),
    recipientStreet: v.string(),
    recipientCity: v.string(),
    recipientUid: v.optional(v.string()),
    taxMode: v.string(),
    taxRate: v.number(),
    taxNote: v.optional(v.string()),
    taxBreakdown: v.optional(v.array(taxBreakdownEntry)),
    netAmount: v.number(),
    vatAmount: v.number(),
    grossAmount: v.number(),
    items: v.array(lineItem),
    status: v.string(),
    confirmedDate: v.optional(v.string()),
    discardedDate: v.optional(v.string()),
    sentDate: v.optional(v.string()),
    sentTo: v.optional(v.string()),
    pdfStorageId: v.optional(v.id("_storage")),
    angebotId: v.optional(v.id("angebots")),
    rechnungIds: v.optional(v.array(v.id("outgoingInvoices"))),
    recurringTemplateId: v.optional(v.id("recurringOrderTemplates")),
    recurringOccurrenceId: v.optional(v.id("recurringOrderOccurrences")),
    scheduledFor: v.optional(v.string()),
    createdAutomatically: v.optional(v.boolean()),
    paymentTerms: v.string(),
    footer: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("userId", ["userId"])
    .index("number", ["userId", "number"])
    .index("userId_createdAt", ["userId", "createdAt"])
    .index("recurringTemplateId", ["recurringTemplateId"]),

  recurringOrderTemplates: defineTable({
    userId: v.id("users"),
    title: v.string(),
    customerId: v.optional(v.id("customers")),
    recipientName: v.string(),
    recipientStreet: v.string(),
    recipientCity: v.string(),
    recipientUid: v.optional(v.string()),
    taxMode: v.string(),
    taxRate: v.number(),
    taxNote: v.optional(v.string()),
    items: v.array(lineItem),
    paymentTerms: v.string(),
    footer: v.optional(v.string()),
    frequency: v.union(v.literal("monthly"), v.literal("yearly")),
    interval: v.number(),
    startDate: v.string(),
    timezone: v.string(),
    endMode: v.union(v.literal("never"), v.literal("on_date"), v.literal("after_occurrences")),
    endDate: v.optional(v.string()),
    maxOccurrences: v.optional(v.number()),
    anchorDay: v.number(),
    anchorMonth: v.optional(v.number()),
    lastDayOfMonth: v.boolean(),
    status: v.union(v.literal("active"), v.literal("paused"), v.literal("completed"), v.literal("error")),
    nextOccurrenceDate: v.optional(v.string()),
    lastOccurrenceDate: v.optional(v.string()),
    occurrenceCount: v.number(),
    generatedCount: v.number(),
    errorMessage: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("userId", ["userId"])
    .index("userId_status", ["userId", "status"])
    .index("status_nextOccurrenceDate", ["status", "nextOccurrenceDate"]),

  recurringOrderOccurrences: defineTable({
    userId: v.id("users"),
    templateId: v.id("recurringOrderTemplates"),
    occurrenceIndex: v.number(),
    occurrenceDate: v.string(),
    occurrenceKey: v.string(),
    status: v.union(
      v.literal("scheduled"),
      v.literal("processing"),
      v.literal("generated"),
      v.literal("skipped"),
      v.literal("failed"),
    ),
    generatedOrderId: v.optional(v.id("auftrags")),
    attemptCount: v.number(),
    errorCode: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    createdAt: v.number(),
    processedAt: v.optional(v.number()),
  })
    .index("templateId_occurrenceDate", ["templateId", "occurrenceDate"])
    .index("status_occurrenceDate", ["status", "occurrenceDate"])
    .index("userId_templateId", ["userId", "templateId"]),

  outgoingInvoices: defineTable({
    userId: v.id("users"),
    auftragId: v.id("auftrags"),
    number: v.string(),
    type: v.string(),
    date: v.string(),
    deliveryDate: v.optional(v.string()),
    periodStart: v.optional(v.string()),
    periodEnd: v.optional(v.string()),
    customerId: v.optional(v.id("customers")),
    recipientName: v.string(),
    recipientStreet: v.string(),
    recipientCity: v.string(),
    recipientUid: v.optional(v.string()),
    taxMode: v.string(),
    taxRate: v.number(),
    taxNote: v.optional(v.string()),
    taxBreakdown: v.optional(v.array(taxBreakdownEntry)),
    netAmount: v.number(),
    vatAmount: v.number(),
    grossAmount: v.number(),
    items: v.array(lineItem),
    status: v.string(),
    lockedAt: v.optional(v.number()),
    paidDate: v.optional(v.string()),
    sentDate: v.optional(v.string()),
    sentTo: v.optional(v.string()),
    stornoOf: v.optional(v.string()),
    stornoNumber: v.optional(v.string()),
    paymentTerms: v.string(),
    footer: v.optional(v.string()),
    pdfStorageId: v.optional(v.id("_storage")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("userId", ["userId"])
    .index("number", ["userId", "number"])
    .index("userId_createdAt", ["userId", "createdAt"]),

  incomingInvoices: defineTable({
    userId: v.id("users"),
    number: v.string(),
    date: v.string(),
    deliveryDate: v.optional(v.string()),
    issuerName: v.string(),
    issuerStreet: v.optional(v.string()),
    issuerCity: v.optional(v.string()),
    issuerUid: v.optional(v.string()),
    taxRate: v.number(),
    netAmount: v.number(),
    vatAmount: v.number(),
    grossAmount: v.number(),
    category: v.optional(v.string()),
    description: v.optional(v.string()),
    paymentTerms: v.optional(v.string()),
    iban: v.optional(v.string()),
    bic: v.optional(v.string()),
    status: v.string(),
    paidDate: v.optional(v.string()),
    paidAmount: v.optional(v.number()),
    fileStorageId: v.optional(v.id("_storage")),
    createdAt: v.number(),
  }).index("userId", ["userId"]),

  dunningLetters: defineTable({
    userId: v.id("users"),
    invoiceId: v.id("outgoingInvoices"),
    invoiceNumber: v.string(),
    type: v.string(),
    date: v.string(),
    amount: v.number(),
    pdfStorageId: v.optional(v.id("_storage")),
    createdAt: v.number(),
  }).index("invoiceId", ["invoiceId"]).index("userId", ["userId"]),

  numberSequences: defineTable({
    userId: v.id("users"),
    year: v.number(),
    nextNumber: v.number(),
    createdAt: v.number(),
  }).index("userId_year", ["userId", "year"]),

  backups: defineTable({
    userId: v.id("users"),
    storageId: v.id("_storage"),
    fileName: v.string(),
    sizeBytes: v.number(),
    recordCount: v.number(),
    type: v.string(),
    createdAt: v.number(),
  }).index("userId", ["userId"]).index("createdAt", ["createdAt"]),

  sessions: defineTable({
    userId: v.id("users"),
    token: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
  }).index("token", ["token"]).index("userId", ["userId"]),

  skillDownloads: defineTable({
    email: v.string(),
    token: v.string(),
    sessionId: v.string(),
    createdAt: v.number(),
    downloadedAt: v.optional(v.number()),
  }).index("token", ["token"]).index("email", ["email"]),

  skillVersions: defineTable({
    version: v.string(),
    description: v.string(),
    storageId: v.id("_storage"),
    fileName: v.string(),
    sizeBytes: v.number(),
    checksum: v.string(),
    isLatest: v.boolean(),
    releaseNotes: v.optional(v.string()),
    createdAt: v.number(),
  }).index("isLatest", ["isLatest"]).index("version", ["version"]),

  settings: defineTable({
    userId: v.id("users"),
    rechnungMode: v.string(),
    defaultTaxMode: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("userId", ["userId"]),

  auditLog: defineTable({
    userId: v.id("users"),
    action: v.string(),
    details: v.string(),
    timestamp: v.number(),
  }).index("userId", ["userId"]),

  waitlist: defineTable({
    email: v.string(),
    createdAt: v.number(),
  }).index("email", ["email"]),
});
